// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230526094348_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Authorization.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Policy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 180, DateTimeKind.Unspecified).AddTicks(37), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Name = "SeeAllUsers"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 180, DateTimeKind.Unspecified).AddTicks(37), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Name = "UpdateInstructorProfile"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 180, DateTimeKind.Unspecified).AddTicks(37), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Name = "UpdateUserProfile"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Authorization.PolicyRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId", "PolicyId");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyRole");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PolicyId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 180, DateTimeKind.Unspecified).AddTicks(5318), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PolicyId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 180, DateTimeKind.Unspecified).AddTicks(5318), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PolicyId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 180, DateTimeKind.Unspecified).AddTicks(5318), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 3
                        },
                        new
                        {
                            RoleId = 3,
                            PolicyId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 180, DateTimeKind.Unspecified).AddTicks(5318), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.Authorization.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 181, DateTimeKind.Unspecified).AddTicks(9399), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 181, DateTimeKind.Unspecified).AddTicks(9399), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Name = "Student"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 181, DateTimeKind.Unspecified).AddTicks(9399), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Name = "Instructor"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarModelId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarModelId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            RegistrationNumber = "TM 993 KKB",
                            Vin = "51C7TL35X5SD42589"
                        },
                        new
                        {
                            Id = 2,
                            CarModelId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            RegistrationNumber = "TM 152 ZYP",
                            Vin = "XMWZRVN1XKI817577"
                        },
                        new
                        {
                            Id = 3,
                            CarModelId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            RegistrationNumber = "TM 080 HGC",
                            Vin = "9FXEFSCN81EQ28486"
                        },
                        new
                        {
                            Id = 4,
                            CarModelId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            RegistrationNumber = "TM 381 PAF",
                            Vin = "LC6K6LLWM6VO10486"
                        },
                        new
                        {
                            Id = 5,
                            CarModelId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            RegistrationNumber = "TM 083 GCW",
                            Vin = "G6E7FZQT48F430415"
                        },
                        new
                        {
                            Id = 6,
                            CarModelId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            RegistrationNumber = "TM 007 XED",
                            Vin = "RTTWPHDC6CKV32139"
                        },
                        new
                        {
                            Id = 7,
                            CarModelId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            RegistrationNumber = "TM 072 KRH",
                            Vin = "QKFRHOE1MMD158061"
                        },
                        new
                        {
                            Id = 8,
                            CarModelId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            RegistrationNumber = "TM 113 IJB",
                            Vin = "PP1NKHQCZ3E998050"
                        },
                        new
                        {
                            Id = 9,
                            CarModelId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            RegistrationNumber = "TM 164 LRX",
                            Vin = "C7AFRP1AVVNT69301"
                        },
                        new
                        {
                            Id = 10,
                            CarModelId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            RegistrationNumber = "TM 833 BKH",
                            Vin = "UARCFYGD5VKN48345"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarGear")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Year")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CarModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarGear = 1,
                            Color = "purple",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Manufacturer = "Dacia",
                            Model = "Sandero",
                            Year = new DateTime(2019, 3, 26, 19, 57, 9, 292, DateTimeKind.Local).AddTicks(7509)
                        },
                        new
                        {
                            Id = 2,
                            CarGear = 1,
                            Color = "red",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Manufacturer = "Skoda",
                            Model = "Fabia",
                            Year = new DateTime(2019, 12, 16, 4, 10, 6, 939, DateTimeKind.Local).AddTicks(9898)
                        },
                        new
                        {
                            Id = 3,
                            CarGear = 2,
                            Color = "blue",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Manufacturer = "Renault",
                            Model = "Zoe",
                            Year = new DateTime(2020, 12, 18, 21, 50, 18, 189, DateTimeKind.Local).AddTicks(2838)
                        },
                        new
                        {
                            Id = 4,
                            CarGear = 2,
                            Color = "green",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Manufacturer = "Skoda",
                            Model = "Fabia",
                            Year = new DateTime(2019, 10, 25, 23, 11, 52, 157, DateTimeKind.Local).AddTicks(9957)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Identity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Birthday")
                        .HasMaxLength(50)
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1976, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Lawrence_Heidenreich@yahoo.com",
                            FirstName = "Lawrence",
                            LastName = "Heidenreich",
                            Password = "test",
                            PhoneNumber = "+40 746 609 730",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1978, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Dominic39@yahoo.com",
                            FirstName = "Dominic",
                            LastName = "Feeney",
                            Password = "test",
                            PhoneNumber = "+40 749 288 525",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1989, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Hattie_Kling89@hotmail.com",
                            FirstName = "Hattie",
                            LastName = "Kling",
                            Password = "test",
                            PhoneNumber = "+40 746 525 816",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(1993, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Tasha_Jakubowski11@gmail.com",
                            FirstName = "Tasha",
                            LastName = "Jakubowski",
                            Password = "test",
                            PhoneNumber = "+40 747 184 426",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(1974, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Caroline88@hotmail.com",
                            FirstName = "Caroline",
                            LastName = "Muller",
                            Password = "test",
                            PhoneNumber = "+40 746 599 748",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateTime(1997, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Ricardo97@yahoo.com",
                            FirstName = "Ricardo",
                            LastName = "Gleason",
                            Password = "test",
                            PhoneNumber = "+40 745 241 418",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateTime(1978, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Levi21@yahoo.com",
                            FirstName = "Levi",
                            LastName = "Beahan",
                            Password = "test",
                            PhoneNumber = "+40 741 302 517",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateTime(1995, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Tabitha.Russel3@yahoo.com",
                            FirstName = "Tabitha",
                            LastName = "Russel",
                            Password = "test",
                            PhoneNumber = "+40 745 808 485",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 9,
                            Birthday = new DateTime(1981, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Florence_Spinka@gmail.com",
                            FirstName = "Florence",
                            LastName = "Spinka",
                            Password = "test",
                            PhoneNumber = "+40 742 972 208",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            Birthday = new DateTime(1986, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Molly71@gmail.com",
                            FirstName = "Molly",
                            LastName = "Deckow",
                            Password = "test",
                            PhoneNumber = "+40 743 678 572",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 11,
                            Birthday = new DateTime(1980, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Marie.Rolfson@hotmail.com",
                            FirstName = "Marie",
                            LastName = "Rolfson",
                            Password = "test",
                            PhoneNumber = "+40 748 985 223",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 12,
                            Birthday = new DateTime(1998, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Kate.Reynolds43@gmail.com",
                            FirstName = "Kate",
                            LastName = "Reynolds",
                            Password = "test",
                            PhoneNumber = "+40 748 975 984",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 13,
                            Birthday = new DateTime(1973, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Willie_Kertzmann47@yahoo.com",
                            FirstName = "Willie",
                            LastName = "Kertzmann",
                            Password = "test",
                            PhoneNumber = "+40 744 836 590",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 14,
                            Birthday = new DateTime(1990, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Ronnie_Boyle27@gmail.com",
                            FirstName = "Ronnie",
                            LastName = "Boyle",
                            Password = "test",
                            PhoneNumber = "+40 740 773 284",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            Birthday = new DateTime(1992, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Russell_Corkery@yahoo.com",
                            FirstName = "Russell",
                            LastName = "Corkery",
                            Password = "test",
                            PhoneNumber = "+40 741 645 125",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            Birthday = new DateTime(1980, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Allen31@gmail.com",
                            FirstName = "Allen",
                            LastName = "Barton",
                            Password = "test",
                            PhoneNumber = "+40 741 666 019",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            Birthday = new DateTime(1996, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Gregg26@yahoo.com",
                            FirstName = "Gregg",
                            LastName = "Harber",
                            Password = "test",
                            PhoneNumber = "+40 749 413 264",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 18,
                            Birthday = new DateTime(1995, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Barbara.Predovic67@gmail.com",
                            FirstName = "Barbara",
                            LastName = "Predovic",
                            Password = "test",
                            PhoneNumber = "+40 742 591 086",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 19,
                            Birthday = new DateTime(1985, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Casey42@hotmail.com",
                            FirstName = "Casey",
                            LastName = "Hagenes",
                            Password = "test",
                            PhoneNumber = "+40 744 700 580",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 20,
                            Birthday = new DateTime(1994, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Carrie47@yahoo.com",
                            FirstName = "Carrie",
                            LastName = "Johnson",
                            Password = "test",
                            PhoneNumber = "+40 747 645 343",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 21,
                            Birthday = new DateTime(1983, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Elvira51@gmail.com",
                            FirstName = "Elvira",
                            LastName = "Conroy",
                            Password = "test",
                            PhoneNumber = "+40 741 130 401",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 22,
                            Birthday = new DateTime(1979, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Justin98@yahoo.com",
                            FirstName = "Justin",
                            LastName = "Crist",
                            Password = "test",
                            PhoneNumber = "+40 748 305 797",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            Birthday = new DateTime(1996, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Shannon24@gmail.com",
                            FirstName = "Shannon",
                            LastName = "Spencer",
                            Password = "test",
                            PhoneNumber = "+40 740 885 568",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 24,
                            Birthday = new DateTime(1988, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Paul32@hotmail.com",
                            FirstName = "Paul",
                            LastName = "Hamill",
                            Password = "test",
                            PhoneNumber = "+40 748 860 452",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 25,
                            Birthday = new DateTime(1973, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Sylvia.Von58@yahoo.com",
                            FirstName = "Sylvia",
                            LastName = "Von",
                            Password = "test",
                            PhoneNumber = "+40 742 814 763",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 26,
                            Birthday = new DateTime(1977, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Ollie.Grady@hotmail.com",
                            FirstName = "Ollie",
                            LastName = "Grady",
                            Password = "test",
                            PhoneNumber = "+40 741 660 734",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 27,
                            Birthday = new DateTime(1988, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Courtney.Weissnat@yahoo.com",
                            FirstName = "Courtney",
                            LastName = "Weissnat",
                            Password = "test",
                            PhoneNumber = "+40 743 488 529",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 28,
                            Birthday = new DateTime(1987, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Billy.Schmeler29@gmail.com",
                            FirstName = "Billy",
                            LastName = "Schmeler",
                            Password = "test",
                            PhoneNumber = "+40 745 788 434",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 29,
                            Birthday = new DateTime(1983, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Ellis.Rath@gmail.com",
                            FirstName = "Ellis",
                            LastName = "Rath",
                            Password = "test",
                            PhoneNumber = "+40 745 539 503",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 30,
                            Birthday = new DateTime(1995, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Eunice_Hartmann84@hotmail.com",
                            FirstName = "Eunice",
                            LastName = "Hartmann",
                            Password = "test",
                            PhoneNumber = "+40 746 038 497",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 31,
                            Birthday = new DateTime(1973, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Leon8@gmail.com",
                            FirstName = "Leon",
                            LastName = "Bahringer",
                            Password = "test",
                            PhoneNumber = "+40 741 467 367",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 32,
                            Birthday = new DateTime(1977, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Rex_Crist92@hotmail.com",
                            FirstName = "Rex",
                            LastName = "Crist",
                            Password = "test",
                            PhoneNumber = "+40 743 797 312",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 33,
                            Birthday = new DateTime(1975, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Larry_Feil@yahoo.com",
                            FirstName = "Larry",
                            LastName = "Feil",
                            Password = "test",
                            PhoneNumber = "+40 746 837 518",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 34,
                            Birthday = new DateTime(1975, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Roberto64@hotmail.com",
                            FirstName = "Roberto",
                            LastName = "Johnson",
                            Password = "test",
                            PhoneNumber = "+40 744 554 287",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 35,
                            Birthday = new DateTime(1989, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Ollie_Rau@gmail.com",
                            FirstName = "Ollie",
                            LastName = "Rau",
                            Password = "test",
                            PhoneNumber = "+40 749 185 137",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 36,
                            Birthday = new DateTime(1975, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Joshua_Gislason79@yahoo.com",
                            FirstName = "Joshua",
                            LastName = "Gislason",
                            Password = "test",
                            PhoneNumber = "+40 747 875 516",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 37,
                            Birthday = new DateTime(1997, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Jacquelyn93@gmail.com",
                            FirstName = "Jacquelyn",
                            LastName = "Abbott",
                            Password = "test",
                            PhoneNumber = "+40 745 897 819",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 38,
                            Birthday = new DateTime(1986, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Courtney46@hotmail.com",
                            FirstName = "Courtney",
                            LastName = "Konopelski",
                            Password = "test",
                            PhoneNumber = "+40 745 367 305",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            Birthday = new DateTime(1988, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Don_VonRueden49@hotmail.com",
                            FirstName = "Don",
                            LastName = "VonRueden",
                            Password = "test",
                            PhoneNumber = "+40 748 036 666",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 40,
                            Birthday = new DateTime(1975, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Isabel_Barrows@hotmail.com",
                            FirstName = "Isabel",
                            LastName = "Barrows",
                            Password = "test",
                            PhoneNumber = "+40 748 872 640",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 41,
                            Birthday = new DateTime(1998, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Duane_Murphy76@yahoo.com",
                            FirstName = "Duane",
                            LastName = "Murphy",
                            Password = "test",
                            PhoneNumber = "+40 744 593 423",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 42,
                            Birthday = new DateTime(1991, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Homer.Purdy@gmail.com",
                            FirstName = "Homer",
                            LastName = "Purdy",
                            Password = "test",
                            PhoneNumber = "+40 746 482 790",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 43,
                            Birthday = new DateTime(1977, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Carolyn14@yahoo.com",
                            FirstName = "Carolyn",
                            LastName = "Deckow",
                            Password = "test",
                            PhoneNumber = "+40 747 021 182",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 44,
                            Birthday = new DateTime(1989, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Vivian.Maggio22@hotmail.com",
                            FirstName = "Vivian",
                            LastName = "Maggio",
                            Password = "test",
                            PhoneNumber = "+40 742 063 443",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 45,
                            Birthday = new DateTime(1991, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Ramon73@gmail.com",
                            FirstName = "Ramon",
                            LastName = "O'Conner",
                            Password = "test",
                            PhoneNumber = "+40 749 795 409",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 46,
                            Birthday = new DateTime(1979, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Roger_Brekke44@hotmail.com",
                            FirstName = "Roger",
                            LastName = "Brekke",
                            Password = "test",
                            PhoneNumber = "+40 740 449 287",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 47,
                            Birthday = new DateTime(1995, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Ralph66@gmail.com",
                            FirstName = "Ralph",
                            LastName = "Ankunding",
                            Password = "test",
                            PhoneNumber = "+40 749 396 483",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 48,
                            Birthday = new DateTime(1993, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Garrett14@gmail.com",
                            FirstName = "Garrett",
                            LastName = "Connelly",
                            Password = "test",
                            PhoneNumber = "+40 740 621 804",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 49,
                            Birthday = new DateTime(1991, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Ginger.Armstrong@gmail.com",
                            FirstName = "Ginger",
                            LastName = "Armstrong",
                            Password = "test",
                            PhoneNumber = "+40 743 272 815",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 50,
                            Birthday = new DateTime(1979, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 1, 11, 50, 43, 880, DateTimeKind.Unspecified).AddTicks(7923), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            Email = "Kelly_Pouros@yahoo.com",
                            FirstName = "Kelly",
                            LastName = "Pouros",
                            Password = "test",
                            PhoneNumber = "+40 746 068 948",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GearType")
                        .HasColumnType("int");

                    b.Property<int>("IdentityId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(7458), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            GearType = 1,
                            IdentityId = 1,
                            Location = "Strada Crișul 7"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(7458), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            GearType = 1,
                            IdentityId = 4,
                            Location = "Strada Crișul 7"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(7458), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            GearType = 1,
                            IdentityId = 7,
                            Location = "Strada Crișul 7"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(7458), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            GearType = 1,
                            IdentityId = 8,
                            Location = "Strada Crișul 7"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(7458), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            GearType = 1,
                            IdentityId = 10,
                            Location = "Strada Crișul 7"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(7458), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            GearType = 2,
                            IdentityId = 13,
                            Location = "Strada Crișul 7"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(7458), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            GearType = 2,
                            IdentityId = 24,
                            Location = "Strada Crișul 7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(7458), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            GearType = 2,
                            IdentityId = 25,
                            Location = "Strada Crișul 7"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(7458), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            GearType = 2,
                            IdentityId = 26,
                            Location = "Strada Crișul 7"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(7458), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            GearType = 2,
                            IdentityId = 28,
                            Location = "Strada Crișul 7"
                        });
                });

            modelBuilder.Entity("Domain.Entities.InstructorCar", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InstructorId", "CarId");

                    b.HasIndex("CarId");

                    b.ToTable("InstructorCars");

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            CarId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(6937), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 1
                        },
                        new
                        {
                            InstructorId = 1,
                            CarId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(6937), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 2
                        },
                        new
                        {
                            InstructorId = 2,
                            CarId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(6937), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 3
                        },
                        new
                        {
                            InstructorId = 3,
                            CarId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(6937), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 4
                        },
                        new
                        {
                            InstructorId = 4,
                            CarId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(6937), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 5
                        },
                        new
                        {
                            InstructorId = 5,
                            CarId = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(6937), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 6
                        },
                        new
                        {
                            InstructorId = 6,
                            CarId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(6937), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 7
                        },
                        new
                        {
                            InstructorId = 7,
                            CarId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(6937), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 8
                        },
                        new
                        {
                            InstructorId = 8,
                            CarId = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(6937), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 9
                        },
                        new
                        {
                            InstructorId = 9,
                            CarId = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(6937), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 10
                        },
                        new
                        {
                            InstructorId = 10,
                            CarId = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 12, 43, 48, 178, DateTimeKind.Unspecified).AddTicks(6937), new TimeSpan(0, 3, 0, 0, 0)),
                            CreatedBy = "System Migration",
                            Id = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LessonStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("ReviewId")
                        .IsUnique()
                        .HasFilter("[ReviewId] IS NOT NULL");

                    b.HasIndex("StudentId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 179, DateTimeKind.Unspecified).AddTicks(8598), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            InstructorId = 1,
                            LessonStatus = 0,
                            StartTime = new DateTimeOffset(new DateTime(2023, 7, 25, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 179, DateTimeKind.Unspecified).AddTicks(8598), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            InstructorId = 2,
                            LessonStatus = 0,
                            StartTime = new DateTimeOffset(new DateTime(2023, 7, 25, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 179, DateTimeKind.Unspecified).AddTicks(8598), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            InstructorId = 1,
                            LessonStatus = 0,
                            StartTime = new DateTimeOffset(new DateTime(2023, 7, 25, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GearType")
                        .HasColumnType("int");

                    b.Property<int>("IdentityId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 181, DateTimeKind.Unspecified).AddTicks(9696), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            GearType = 1,
                            IdentityId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 5, 26, 9, 43, 48, 181, DateTimeKind.Unspecified).AddTicks(9696), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System Seeding",
                            GearType = 1,
                            IdentityId = 7
                        });
                });

            modelBuilder.Entity("Domain.Entities.Authorization.PolicyRole", b =>
                {
                    b.HasOne("Domain.Entities.Authorization.Policy", "Policy")
                        .WithMany("PolicyRoles")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Authorization.Role", "Role")
                        .WithMany("PolicyRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Car", b =>
                {
                    b.HasOne("Domain.Entities.CarModel", "CarModel")
                        .WithMany("Cars")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("Domain.Entities.Identity", b =>
                {
                    b.HasOne("Domain.Entities.Authorization.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Instructor", b =>
                {
                    b.HasOne("Domain.Entities.Identity", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Domain.Entities.InstructorCar", b =>
                {
                    b.HasOne("Domain.Entities.Car", "Car")
                        .WithMany("InstructorCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Instructor", "Instructor")
                        .WithMany("InstructorCars")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Domain.Entities.Lesson", b =>
                {
                    b.HasOne("Domain.Entities.Instructor", "Instructor")
                        .WithMany("Lessons")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Review", "Review")
                        .WithOne("Lesson")
                        .HasForeignKey("Domain.Entities.Lesson", "ReviewId");

                    b.HasOne("Domain.Entities.Student", "Student")
                        .WithMany("Lessons")
                        .HasForeignKey("StudentId");

                    b.Navigation("Instructor");

                    b.Navigation("Review");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.HasOne("Domain.Entities.Identity", "Identity")
                        .WithMany("Students")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Domain.Entities.Authorization.Policy", b =>
                {
                    b.Navigation("PolicyRoles");
                });

            modelBuilder.Entity("Domain.Entities.Authorization.Role", b =>
                {
                    b.Navigation("PolicyRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Car", b =>
                {
                    b.Navigation("InstructorCars");
                });

            modelBuilder.Entity("Domain.Entities.CarModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Domain.Entities.Identity", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Domain.Entities.Instructor", b =>
                {
                    b.Navigation("InstructorCars");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.Entities.Review", b =>
                {
                    b.Navigation("Lesson")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
